CREATE DATABASE IF NOT EXISTS SistemaBancario;
USE SistemaBancario;
CREATE TABLE IF NOT EXISTS Account(
    ID CHAR(20) NOT NULL UNIQUE PRIMARY KEY,
    Nome VARCHAR(50) NOT NULL,
    Cognome VARCHAR(50) NOT NULL
);
CREATE TABLE IF NOT EXISTS Transazione(
    ID VARCHAR(40) NOT NULL UNIQUE PRIMARY KEY,
    amount DECIMAL NOT NULL,
    dataOra DATETIME NOT NULL,
    CONSTRAINT fk_Mittente FOREIGN KEY (Account) REFERENCES SistemaBancario.Account (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT fk_Ddedstinatario FOREIGN KEY (Account) REFERENCES SistemaBancario.Account (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);