CREATE DATABASE IF NOT EXISTS SistemaBancario;
USE SistemaBancario;
CREATE TABLE IF NOT EXISTS Account(
    ID CHAR(20) NOT NULL UNIQUE PRIMARY KEY,
    Nome VARCHAR(50) NOT NULL,
    Cognome VARCHAR(50) NOT NULL
);
CREATE TABLE IF NOT EXISTS Transazione(
    ID VARCHAR(40) NOT NULL UNIQUE PRIMARY KEY,
    amount DECIMAL NOT NULL,
    dataOra DATETIME NOT NULL,
    mittente CHAR(20) NOT NULL,
    destinatario CHAR(20) NOT NULL,
    FOREIGN KEY (mittente) REFERENCES Account (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
    FOREIGN KEY (destinatario) REFERENCES Account (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);

ALTER TABLE Account ADD COLUMN Saldo DECIMAL NOT NULL DEFAULT 0;